# Generated by Django 3.0 on 2020-03-15 04:21

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, '硅胶产品'), (2, '五金产品'), (3, '电子产品'), (4, '塑胶产品'), (5, '木制产品'), (6, '其他产品')], verbose_name='产品大类')),
                ('sub_type', models.CharField(help_text='用英文填写产品子类', max_length=32, unique=True, verbose_name='产品子类')),
                ('pub_date', models.DateField(auto_now=True, verbose_name='添加日期')),
                ('is_delete', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': '产品类别',
                'verbose_name_plural': '产品类别',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(default='china good gifts', max_length=128)),
                ('seo_desc', models.CharField(default='china good gifts', max_length=256)),
                ('pub_date', models.DateField(auto_now=True, verbose_name='添加日期')),
                ('pro_number', models.CharField(max_length=32, unique=True, verbose_name='产品编号')),
                ('pro_name', models.CharField(default='product', max_length=30, verbose_name='产品名称')),
                ('pro_size', models.CharField(default='custom made', max_length=64, verbose_name='产品尺寸')),
                ('pro_model', models.CharField(default='custom made', max_length=64, verbose_name='产品型号')),
                ('pro_pack', models.CharField(default='custom made', max_length=64, verbose_name='产品包装')),
                ('pro_color', models.CharField(blank=True, max_length=1024)),
                ('pro_weight', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='单重(g)')),
                ('pro_pic', models.CharField(blank=True, max_length=1024)),
                ('pro_desc', ckeditor.fields.RichTextField()),
                ('is_delete', models.IntegerField(default=0)),
                ('is_edit', models.IntegerField(default=0)),
                ('sub_type', models.ForeignKey(max_length=32, on_delete=django.db.models.deletion.CASCADE, to='webapi.ProductsType', verbose_name='产品子类')),
            ],
            options={
                'verbose_name': '产品目录',
                'verbose_name_plural': '产品目录',
            },
        ),
    ]
