# Generated by Django 3.0.5 on 2020-09-24 09:38

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(max_length=64)),
                ('seo_desc', models.CharField(max_length=256)),
                ('is_use', models.IntegerField(default=0)),
                ('company_name', models.CharField(blank=True, max_length=64, null=True)),
                ('company_addr', models.CharField(blank=True, max_length=256, null=True)),
                ('logo_svg', models.TextField(blank=True, null=True)),
                ('is_delete', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ProductsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=32, null=True, verbose_name='产品总类')),
                ('pub_date', models.DateField(auto_now=True, verbose_name='添加日期')),
                ('is_delete', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': '产品类别',
                'verbose_name_plural': '产品类别',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(default='china good gifts', max_length=128)),
                ('seo_desc', models.CharField(default='china good gifts', max_length=256)),
                ('pub_date', models.DateField(auto_now=True, verbose_name='添加日期')),
                ('pro_number', models.CharField(max_length=32, unique=True, verbose_name='产品编号')),
                ('pro_name', models.CharField(default='product', max_length=30, verbose_name='产品名称')),
                ('pro_price', models.DecimalField(decimal_places=2, default=100, max_digits=10, verbose_name='产品单价')),
                ('click_num', models.IntegerField(default=0, verbose_name='点击数')),
                ('sold_num', models.IntegerField(default=0, verbose_name='商品销售量')),
                ('fav_num', models.IntegerField(default=0, verbose_name='收藏数')),
                ('goods_num', models.IntegerField(default=0, verbose_name='库存数')),
                ('is_new', models.IntegerField(default=0, verbose_name='是否新品')),
                ('is_hot', models.IntegerField(default=0, verbose_name='是否热销')),
                ('is_discount', models.IntegerField(default=0)),
                ('pro_discount', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('pro_size', models.CharField(default='custom made', max_length=64, verbose_name='产品尺寸')),
                ('pro_model', models.CharField(default='custom made', max_length=64, verbose_name='产品型号')),
                ('pro_pack', models.CharField(default='custom made', max_length=64, verbose_name='产品包装')),
                ('pro_color', models.CharField(blank=True, max_length=1024)),
                ('pro_weight', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='单重(g)')),
                ('pro_desc', ckeditor.fields.RichTextField()),
                ('is_delete', models.IntegerField(default=0)),
                ('is_edit', models.IntegerField(default=0)),
                ('sub_type', models.ForeignKey(blank=True, max_length=32, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapi.ProductsType', verbose_name='产品子类')),
            ],
            options={
                'verbose_name': '产品目录',
                'verbose_name_plural': '产品目录',
            },
        ),
    ]
