# Generated by Django 3.0 on 2020-03-17 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='pro_pic',
        ),
        migrations.AddField(
            model_name='products',
            name='click_num',
            field=models.IntegerField(default=0, verbose_name='点击数'),
        ),
        migrations.AddField(
            model_name='products',
            name='fav_num',
            field=models.IntegerField(default=0, verbose_name='收藏数'),
        ),
        migrations.AddField(
            model_name='products',
            name='goods_num',
            field=models.IntegerField(default=0, verbose_name='库存数'),
        ),
        migrations.AddField(
            model_name='products',
            name='is_discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='products',
            name='is_hot',
            field=models.IntegerField(default=0, verbose_name='是否热销'),
        ),
        migrations.AddField(
            model_name='products',
            name='is_new',
            field=models.IntegerField(default=0, verbose_name='是否新品'),
        ),
        migrations.AddField(
            model_name='products',
            name='pro_discount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
        migrations.AddField(
            model_name='products',
            name='pro_price',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AddField(
            model_name='products',
            name='sold_num',
            field=models.IntegerField(default=0, verbose_name='商品销售量'),
        ),
    ]
