# Generated by Django 3.0.5 on 2020-11-17 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='capacities',
            field=models.CharField(default='custom', max_length=128, verbose_name='容量'),
        ),
        migrations.AddField(
            model_name='products',
            name='imprint_location',
            field=models.CharField(default='custom', max_length=64, verbose_name='logo位置'),
        ),
        migrations.AddField(
            model_name='products',
            name='imprint_methods',
            field=models.CharField(default='custom', max_length=128, verbose_name='logo工艺'),
        ),
        migrations.AddField(
            model_name='products',
            name='imprint_size',
            field=models.CharField(default='custom', max_length=128, verbose_name='logo尺寸'),
        ),
        migrations.AddField(
            model_name='products',
            name='material',
            field=models.CharField(default='custom', max_length=64, verbose_name='材质'),
        ),
        migrations.AddField(
            model_name='products',
            name='moq',
            field=models.IntegerField(default=100, verbose_name='起订量'),
        ),
        migrations.AlterField(
            model_name='products',
            name='pro_color',
            field=models.CharField(blank=True, max_length=1024, verbose_name='产品颜色'),
        ),
    ]
