# Generated by Django 3.0 on 2020-03-19 10:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0003_auto_20200319_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='pro_type',
            # field=models.CharField(default=django.utils.timezone.now, max_length=32),
            field=models.CharField(default='powerbank', max_length=32),
            preserve_default=False,
        ),
    ]
