# Generated by Django 3.0.5 on 2020-12-01 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0003_auto_20201118_0145'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pack_number', models.CharField(blank=True, max_length=64, verbose_name='编号')),
                ('size', models.CharField(default='custom', max_length=128, verbose_name='尺寸')),
                ('material', models.CharField(default='custom', max_length=128, verbose_name='材质')),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='重量')),
                ('description', models.TextField(blank=True, verbose_name='说明')),
                ('is_delete', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ProductsToPacks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateField(auto_now=True, verbose_name='添加日期')),
                ('packs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapi.PackModels')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapi.Products')),
            ],
        ),
        migrations.AddField(
            model_name='packmodels',
            name='products',
            field=models.ManyToManyField(through='webapi.ProductsToPacks', to='webapi.Products'),
        ),
    ]
