# Generated by Django 3.0.5 on 2020-12-07 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0004_auto_20201201_0637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='pro_desc',
        ),
        migrations.AddField(
            model_name='products',
            name='custom',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='products',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='products',
            name='prompt',
            field=models.TextField(blank=True),
        ),
    ]
