# Generated by Django 3.0.5 on 2020-12-07 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0005_auto_20201207_0636'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_type', models.CharField(max_length=64)),
                ('p_content', models.TextField(blank=True)),
                ('pub_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
