# Generated by Django 3.0.5 on 2020-12-08 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0006_producttext'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttext',
            name='p_property',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='producttext',
            name='p_type',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
