# Generated by Django 3.0.5 on 2020-09-24 09:38

import api.models
import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('type', models.IntegerField(choices=[(1, '采购商'), (2, '供应商'), (3, '采购&供应')], verbose_name='客户类别')),
                ('name', models.CharField(default='选填', max_length=100, verbose_name='公司名称')),
                ('lite_name', models.CharField(help_text='如无公司则填联系人或CEO名称', max_length=32, primary_key=True, serialize=False, verbose_name='公司简称')),
                ('address', models.CharField(default='选填', max_length=200, verbose_name='公司地址')),
                ('phone', models.CharField(default='选填', max_length=40, verbose_name='公司电话')),
                ('website', models.URLField(default='https://example.com', verbose_name='网址')),
                ('business', models.CharField(max_length=64, verbose_name='主营业务')),
                ('ceo', models.CharField(default='选填', max_length=50, verbose_name='CEO')),
                ('email', models.EmailField(default='example@email.com', max_length=100, verbose_name='CEO邮箱')),
                ('ceo_phone', models.CharField(default='选填', max_length=20, verbose_name='CEO电话')),
                ('contact_name', models.CharField(max_length=100, verbose_name='联系人')),
                ('contact_email', models.EmailField(max_length=100, verbose_name='联系人邮箱')),
                ('contact_phone', models.CharField(max_length=50, verbose_name='联系人电话')),
                ('status', models.IntegerField(choices=[(1, '合作'), (2, '终止'), (3, '开发')], verbose_name='合作状态')),
                ('line_credits', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='信用额度')),
                ('input_time', models.DateField(auto_now_add=True, verbose_name='添加日期')),
                ('text', models.CharField(default='选填', max_length=480, verbose_name='备注')),
                ('is_delete', models.IntegerField(default=0)),
                ('sales', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.UserInfo', verbose_name='业务')),
            ],
            options={
                'verbose_name': '客户信息',
                'verbose_name_plural': '客户信息',
            },
        ),
        migrations.CreateModel(
            name='OrderCatalog',
            fields=[
                ('order_number', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='订单编号')),
                ('order_date', models.DateField(default=datetime.datetime.now, verbose_name='下单日期')),
                ('deliver_date', models.DateField(verbose_name='订单交期')),
                ('input_date', models.DateField(auto_now=True, verbose_name='录入日期')),
                ('ex_rate', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='汇率')),
                ('order_amount', models.DecimalField(decimal_places=3, max_digits=20, verbose_name='金额')),
                ('order_pic', models.CharField(blank=True, max_length=128, null=True)),
                ('is_done', models.IntegerField(choices=[(0, '正常'), (1, '紧急')], default=0, verbose_name='状态')),
                ('text', models.CharField(default='选填', max_length=480, verbose_name='备注')),
                ('ship_addr', models.CharField(default='暂无', max_length=200, verbose_name='出货地点')),
                ('is_delete', models.IntegerField(default=0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Customers', verbose_name='客户')),
                ('sales', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.UserInfo', verbose_name='业务')),
            ],
            options={
                'verbose_name': '订单目录',
                'verbose_name_plural': '订单目录',
            },
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default=api.models.make_model_number, max_length=64)),
                ('atr', models.IntegerField(choices=[(0, '自有'), (1, '工厂'), (2, '样品')], default=1)),
                ('material', models.IntegerField(default=1)),
                ('size', models.CharField(blank=True, max_length=64, null=True)),
                ('construct', models.CharField(blank=True, max_length=64, null=True)),
                ('pro_date', models.DateField(default=datetime.datetime.now)),
                ('useful_life', models.IntegerField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remarks', models.CharField(blank=True, max_length=256, null=True)),
                ('is_delete', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SubOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(max_length=50, verbose_name='产品名称')),
                ('pro_item', models.IntegerField(choices=[(1, '硅胶'), (2, '五金'), (3, 'USB'), (4, '移动电源'), (5, '其他')], verbose_name='产品类别')),
                ('pro_size', models.CharField(default=0, max_length=64, verbose_name='产品尺寸')),
                ('pro_color', models.CharField(blank=True, max_length=1024)),
                ('pro_pack', models.CharField(default='无', max_length=64, verbose_name='产品包装')),
                ('pro_desc', models.CharField(max_length=400, verbose_name='详细描述')),
                ('pro_qt', models.DecimalField(decimal_places=1, max_digits=20, verbose_name='数量(个)')),
                ('pro_price', models.DecimalField(decimal_places=3, max_digits=20, verbose_name='单价($)')),
                ('pro_weight', models.DecimalField(decimal_places=1, max_digits=20, verbose_name='单重(g)')),
                ('sub_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='订单金额($)')),
                ('sub_input_date', models.DateField(auto_now=True, verbose_name='录入日期')),
                ('is_delete', models.IntegerField(default=0)),
                ('is_purchase', models.IntegerField(default=0)),
                ('is_ship', models.IntegerField(default=0)),
                ('is_account', models.IntegerField(default=0)),
                ('is_reconciliation', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=1)),
                ('order_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_orders', to='api.OrderCatalog', verbose_name='订单编号')),
                ('sales', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.UserInfo', verbose_name='业务')),
            ],
            options={
                'verbose_name': '订单明细',
                'verbose_name_plural': '订单明细',
            },
        ),
        migrations.CreateModel(
            name='ShipOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ship_plan', models.IntegerField(choices=[('国际快递', ((1, 'UPS'), (2, 'FedEx'), (3, 'DHL'))), (4, '国内快递'), (5, '船运'), (6, '自提'), (7, '第三方'), (8, '其他')], verbose_name='出货方式')),
                ('ship_number', models.CharField(max_length=50, verbose_name='出货单号')),
                ('ship_date', models.DateField(default=datetime.datetime.now, verbose_name='出货日期')),
                ('ship_cost', models.DecimalField(decimal_places=4, max_digits=20, verbose_name='出货费用(¥)')),
                ('ship_weight', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='重量(kg)')),
                ('text', models.CharField(default='选填', max_length=480, verbose_name='备注')),
                ('destination', models.CharField(default='American', max_length=32)),
                ('is_delete', models.IntegerField(default=0)),
                ('input_date', models.DateTimeField(auto_now_add=True)),
                ('sales', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.UserInfo', verbose_name='业务')),
                ('ship_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Customers', verbose_name='货代')),
            ],
            options={
                'verbose_name': '出货记录',
                'verbose_name_plural': '出货记录',
            },
        ),
        migrations.CreateModel(
            name='ShipDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ship_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='出货费用(¥)')),
                ('ship_weight', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='出货重量(kg)')),
                ('is_delete', models.IntegerField(default=0)),
                ('ship_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ShipOrder', verbose_name='出货单号')),
                ('sub_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ships', to='api.SubOrder', verbose_name='订单明细')),
            ],
            options={
                'verbose_name': '出货明细',
                'verbose_name_plural': '出货明细',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('purchase_date', models.DateField(default=datetime.datetime.now, verbose_name='采购日期')),
                ('deliver_date', models.DateField(verbose_name='采购交期')),
                ('purchase_number', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='采购单号')),
                ('input_date', models.DateTimeField(auto_now_add=True)),
                ('text', models.CharField(default='选填', max_length=400, verbose_name='备注')),
                ('is_delete', models.IntegerField(default=0)),
                ('purchaser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Customers', verbose_name='供应商')),
                ('sales', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.UserInfo', verbose_name='业务')),
            ],
            options={
                'verbose_name': '采购订单',
                'verbose_name_plural': '采购订单',
            },
        ),
        migrations.CreateModel(
            name='PurchaseDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='采购单价(¥)')),
                ('purchase_qt', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='采购数量(个)')),
                ('purchase_amount', models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='采购金额($)')),
                ('text', models.CharField(default='选填', max_length=400, verbose_name='备注')),
                ('is_delete', models.IntegerField(default=0)),
                ('purchase_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.PurchaseOrder', verbose_name='采购单号')),
                ('sub_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='api.SubOrder', verbose_name='订单明细')),
            ],
            options={
                'verbose_name': '采购明细',
                'verbose_name_plural': '采购明细',
            },
        ),
        migrations.CreateModel(
            name='OrderToModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_price', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('input_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_delete', models.IntegerField(default=0)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.OrderModel')),
                ('order_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.OrderCatalog')),
            ],
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='order_number',
            field=models.ManyToManyField(through='api.OrderToModel', to='api.OrderCatalog'),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_model', to='api.Customers'),
        ),
        migrations.CreateModel(
            name='CustomerAddr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addr_type', models.IntegerField(choices=[(1, 'other'), (0, 'common')], default=1)),
                ('linkman', models.CharField(blank=True, max_length=64, null=True)),
                ('postcode', models.CharField(blank=True, max_length=10, null=True)),
                ('country', models.CharField(blank=True, max_length=64, null=True)),
                ('city', models.CharField(blank=True, max_length=64, null=True)),
                ('addr', models.CharField(blank=True, max_length=256, null=True)),
                ('input_date', models.DateField(auto_now=True)),
                ('is_delete', models.IntegerField(default=0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Customers')),
            ],
        ),
    ]
