# Generated by Django 3.0 on 2020-03-10 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suborder',
            name='pro_color',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
