# Generated by Django 3.0.5 on 2020-11-18 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201117_0251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraddr',
            name='addr_type',
            field=models.IntegerField(choices=[(1, 'other'), (0, 'common')], default=1),
        ),
    ]
