# Generated by Django 3.0 on 2020-03-12 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200310_0543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suborder',
            name='pro_color',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
