# Generated by Django 3.0.5 on 2020-09-24 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('webapi', '0001_initial'),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('up_date', models.DateField(auto_now_add=True)),
                ('md5', models.CharField(max_length=128)),
                ('owner', models.CharField(max_length=32)),
                ('path', models.CharField(max_length=128)),
                ('is_home', models.IntegerField(default=0)),
                ('home_index', models.IntegerField(default=0)),
                ('is_banner', models.IntegerField(default=0)),
                ('is_edit', models.IntegerField(default=0)),
                ('is_used', models.IntegerField(default=0)),
                ('image_alt', models.CharField(default='usb powerbank', max_length=64)),
                ('order_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_image', to='api.OrderCatalog')),
                ('pro_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pro_image', to='webapi.Products')),
            ],
        ),
    ]
