# Generated by Django 3.0 on 2020-03-09 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('up_date', models.DateTimeField(auto_now_add=True)),
                ('md5', models.CharField(max_length=128)),
                ('owner', models.CharField(max_length=32)),
                ('path', models.CharField(max_length=128)),
            ],
        ),
    ]
