# Generated by Django 3.0 on 2020-03-12 15:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='file_path',
            field=models.CharField(default=django.utils.timezone.now, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='home_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='image',
            name='is_banner',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='image',
            name='is_home',
            field=models.IntegerField(default=0),
        ),
    ]
