# Generated by Django 3.0.5 on 2020-12-01 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0004_auto_20201201_0637'),
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='pack_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pack_image', to='webapi.PackModels'),
        ),
    ]
