# Generated by Django 3.0.5 on 2020-12-03 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_image_pack_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='is_cover',
            field=models.IntegerField(default=0),
        ),
    ]
