# Generated by Django 3.0 on 2020-03-14 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_remove_image_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='is_edit',
            field=models.IntegerField(default=0),
        ),
    ]
