# Generated by Django 3.0 on 2020-03-14 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_image_is_edit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='up_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
