# Generated by Django 3.0 on 2020-03-15 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200312_0742'),
        ('webapi', '0001_initial'),
        ('upload', '0005_auto_20200314_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='order_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.OrderCatalog'),
        ),
        migrations.AddField(
            model_name='image',
            name='pro_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapi.Products'),
        ),
    ]
