# Generated by Django 3.0 on 2020-03-15 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200312_0742'),
        ('webapi', '0001_initial'),
        ('upload', '0006_auto_20200315_0421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='order_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_image', to='api.OrderCatalog'),
        ),
        migrations.AlterField(
            model_name='image',
            name='pro_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pro_image', to='webapi.Products'),
        ),
    ]
